# Generated by Django 3.2.13 on 2022-05-31 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='', max_length=10)),
                ('mobile_no', models.CharField(max_length=10)),
                ('adhar_no', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff_Leave_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_portal.staff_details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift_Out_Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('out', models.TimeField(default=datetime.time(13, 39, 45, 881092))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_portal.staff_details')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift_In_Timings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('entry', models.TimeField(default=datetime.time(13, 39, 45, 881092))),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_portal.staff_details')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
