# Generated by Django 3.2.13 on 2022-05-31 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0003_auto_20220531_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_in_timings',
            name='entry',
            field=models.TimeField(default=datetime.time(15, 48, 45, 762517)),
        ),
        migrations.AlterField(
            model_name='shift_out_timings',
            name='out',
            field=models.TimeField(default=datetime.time(15, 48, 45, 762517)),
        ),
    ]
