# Generated by Django 3.2.13 on 2022-06-01 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0006_auto_20220601_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_in_timings',
            name='entry',
            field=models.TimeField(default=datetime.time(12, 25, 58, 746252)),
        ),
        migrations.AlterField(
            model_name='shift_out_timings',
            name='out',
            field=models.TimeField(default=datetime.time(12, 25, 58, 746252)),
        ),
    ]
