# Generated by Django 3.2.13 on 2022-07-06 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0008_auto_20220601_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_in_timings',
            name='entry',
            field=models.TimeField(default=datetime.time(15, 6, 13, 908944)),
        ),
        migrations.AlterField(
            model_name='shift_out_timings',
            name='out',
            field=models.TimeField(default=datetime.time(15, 6, 13, 908944)),
        ),
    ]
