# Generated by Django 3.2.13 on 2022-05-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instuments_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('warranty_in_Years', models.DateField(null=True)),
                ('Guaranty_in_years', models.DateField(null=True)),
                ('amc', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendoor_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendoor_name', models.CharField(max_length=50)),
                ('instument_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
