# Generated by Django 3.2.13 on 2022-05-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test_result', models.CharField(max_length=150)),
                ('test_diagnosis', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='IPD_Department_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GEN', 'General'), ('ICU', 'ICU')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IPD_Patient_Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IPD_Sub_Department_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_portal.ipd_department_details')),
            ],
        ),
        migrations.CreateModel(
            name='OPD_Department_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OPD_Sub_Department_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('opd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_portal.opd_department_details')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Medecines_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(choices=[('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='WF270055', max_length=8, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('addres', models.CharField(choices=[('Ambi Bk', 'Ambi Bk'), ('Ambi Kh', 'Ambi Kh'), ('Anjangaon', 'Anjangaon'), ('Baburdi', 'Baburdi'), ('Bajrangwadi late', 'Bajrangwadi late'), ('Bajrangwadi rular', 'Bajrangwadi rular')], default='', max_length=50)),
                ('mobile_no', models.CharField(max_length=10)),
                ('medecine_issued', models.ManyToManyField(to='patient_portal.Patient_Medecines_details')),
                ('opd', models.ForeignKey(default='OPD', on_delete=django.db.models.deletion.CASCADE, to='patient_portal.opd_department_details')),
                ('opd_sub_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_portal.opd_sub_department_details')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Department_IPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joining', models.DateField(auto_now_add=True, null=True)),
                ('date_discharge', models.DateField(blank=True, null=True)),
                ('bed_allot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.ipd_patient_beds')),
                ('ipd', models.ForeignKey(default='IPD', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.ipd_department_details')),
                ('ipd_sub_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.ipd_sub_department_details')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_portal.patient_details')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('patient_diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_portal.investigation_test')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(choices=[('Ambi Bk', 'Ambi Bk'), ('Ambi Kh', 'Ambi Kh'), ('Anjangaon', 'Anjangaon'), ('Baburdi', 'Baburdi'), ('Bajrangwadi late', 'Bajrangwadi late'), ('Bajrangwadi rular', 'Bajrangwadi rular')], max_length=255, null=True)),
                ('state_ptr', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.state')),
            ],
        ),
    ]
