# Generated by Django 3.2.13 on 2022-05-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_department_ipd',
            name='bed_allot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_portal.ipd_patient_beds'),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='pid',
            field=models.CharField(default='PD461852', max_length=8, unique=True),
        ),
    ]
