# Generated by Django 3.2.13 on 2022-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0003_auto_20220531_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPD_Patient_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='pid',
            field=models.CharField(default='AB931318', max_length=8, unique=True),
        ),
    ]
