# Generated by Django 3.2.13 on 2022-06-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0005_auto_20220531_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipd_patient_beds',
            name='name',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2'), ('D1', 'D1')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='pid',
            field=models.CharField(default='PD545052', max_length=8, unique=True),
        ),
    ]
