# Generated by Django 3.2.13 on 2022-06-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0006_auto_20220601_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='pid',
            field=models.CharField(default='WF310296', max_length=8, unique=True),
        ),
    ]
