# Generated by Django 3.2.13 on 2022-07-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0008_auto_20220601_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine_issued_Count_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='patient_details',
            name='pid',
            field=models.CharField(default='GH617872', max_length=8, unique=True),
        ),
    ]
